MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "models/mobilenet_v2.pth.tar"
  RPN_ONLY: True
  FCOS_ON: True
  BACKBONE:
    CONV_BODY: "MobileNetV2-FPN-RETINANET"
    OUT_CHANNELS: 256
  MOBILENET:
    OUT_CHANNELS: (24, 32, 96, 320)
  RETINANET:
    USE_C5: False # FCOS uses P5 instead of C5
DATASETS:
  TRAIN: ("coco_2014_train", "coco_2014_valminusminival")
  TEST: ("coco_2014_minival",)
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  # Assume 4 gpus
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 16
  WARMUP_METHOD: "constant"